### PR TITLE
More material on handling categorical variables

### PR DESCRIPTION
**Pull request by turtlemonvh**
Count encoding, label encoding, hashing trick

### CODE REVIEW

**Comment by aikho** [comment]
Hello Timothy.

Thank you for your PR. It takes some time to review.

**Comment by aikho** [comment]
Awesome!
These techniques should be definetely included in the list. Thank you.

But I would like to change order and titles a bit.

Also, I doubt about the link to Kaggle comment https://www.kaggle.com/general/16927#95887. Looks like it is about "mean encoding" rather then "count encoding".

I will merge changes soon.

**Comment by turtlemonvh** [comment]
Good catch @aikho - that link should be changed to https://www.kaggle.com/general/16927#95677.

Also let me know if you want me to rebase all these edits into 1 change before merging.

**Comment by aikho** [comment]
Yes, would be great if you will make one single commit instead.

About https://www.kaggle.com/general/16927#95677 This is just two sentences comment. I prefer to keep some degree of awesomeness in the list :) So, I think, only links to more detailed meterials should be included.

**Comment by aikho** [comment]
Tnanks a lot for the PR, @turtlemonvh

**Pull request merged**
